apiVersion: apps/v1
kind: Deployment
metadata:
  name: strings-dowser-deployment
  labels:
    app: strings-dowser
    app.kubernetes.io/version: "0.0.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strings-dowser
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: strings-dowser
    spec:
      containers:
        - name: strings-dowser
          imagePullPolicy: Always
          image: ookiisan/strings-dowser:0.0.3
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 30001
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5